# --- Configuraci贸n de Build para Netlify ---
# Esta secci贸n le dice a Netlify c贸mo construir tu sitio.

[build]
  # Base directory: La carpeta donde vive el c贸digo de tu frontend.
  base = "simulador_frontend"

  # Build command: El comando para compilar tu proyecto de Angular.
  command = "ng build"

  # Publish directory: La carpeta que Netlify debe publicar,
  # relativa a la carpeta 'base'.
  publish = "dist/simulador_frontend"