# --- Configuración de Build para Netlify ---
# Esta sección le dice a Netlify cómo construir tu sitio.

[build]
  # Base directory: La carpeta donde vive el código de tu frontend.
  base = "simulador_frontend"

  # Build command: El comando para compilar tu proyecto de Angular.
  command = "ng build"

  # Publish directory: La carpeta que Netlify debe publicar,
  # relativa a la carpeta 'base'.
  # Apuntamos a la carpeta 'browser' que genera el nuevo builder.
  publish = "dist/simulador_frontend/browser"


# --- Reglas de Redirección para SPA ---
# Esta sección soluciona el problema del "Page not found".

[[redirects]]
  # Para cualquier ruta que no sea un archivo existente...
  from = "/*"
  # ...sirve el index.html principal.
  to = "/index.html"
  # Y devuelve un código de estado 200 (OK).
  status = 200