# Generated by Django 5.2.4 on 2025-07-24 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre personalizado para el árbol', max_length=100)),
                ('tree_type', models.CharField(choices=[('BST', 'Árbol Binario de Búsqueda'), ('AVL', 'Árbol AVL'), ('SPLAY', 'Árbol Splay'), ('B_TREE', 'Árbol B')], default='BST', max_length=10)),
                ('structure', models.JSONField(default=dict, help_text='Estructura del árbol en formato JSON para visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
